import os, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cecp_project.settings')
django.setup()

from django.db import connection
with connection.cursor() as cursor:
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS "landing_event" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "event_type" varchar(50) NOT NULL, "status" varchar(50) NOT NULL, "description" text NOT NULL, "date_range" varchar(100) NOT NULL, "location" varchar(200) NOT NULL, "image" varchar(100) NULL, "is_featured" boolean NOT NULL, "action_url" varchar(200) NOT NULL, "action_text" varchar(50) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
    ''')
print('Table created successfully')
