import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cecp_project.settings')
django.setup()

from django.db import connection

sql = """
CREATE TABLE IF NOT EXISTS landing_projectaccessrequest (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(20) NOT NULL,
    message text NOT NULL,
    reviewed_at timestamp with time zone NULL,
    created_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL REFERENCES landing_project(id) DEFERRABLE INITIALLY DEFERRED,
    requester_id integer NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
    reviewed_by_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT landing_projectaccessrequest_requester_id_project_id_uniq UNIQUE (requester_id, project_id)
);

CREATE INDEX IF NOT EXISTS landing_projectaccessrequest_project_id_idx ON landing_projectaccessrequest (project_id);
CREATE INDEX IF NOT EXISTS landing_projectaccessrequest_requester_id_idx ON landing_projectaccessrequest (requester_id);
CREATE INDEX IF NOT EXISTS landing_projectaccessrequest_reviewed_by_id_idx ON landing_projectaccessrequest (reviewed_by_id);
CREATE INDEX IF NOT EXISTS landing_projectaccessrequest_status_idx ON landing_projectaccessrequest (status);
"""

with connection.cursor() as cursor:
    cursor.execute(sql)
    print("Table landing_projectaccessrequest created successfully!")
