# Generated by Django 6.0.4 on 2026-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Initiative title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the initiative')),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class (e.g., Heroicons or custom SVG identifier)', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the display order on the landing page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Initiatives',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('codename', models.CharField(blank=True, help_text="Internal codename (e.g., 'Sentinel-X')", max_length=100)),
                ('description', models.TextField(help_text='Brief project description')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='List of technologies used (stored as JSON array)')),
                ('image_url', models.URLField(blank=True, help_text='URL to project thumbnail (can be Supabase Storage URL)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this project on the landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('lead', 'Club Lead'), ('co_lead', 'Co-Lead'), ('head', 'Department Head'), ('member', 'Core Member'), ('alumni', 'Alumni')], default='member', max_length=20)),
                ('title', models.CharField(blank=True, help_text="e.g., 'Head of AI/CV Division'", max_length=200)),
                ('avatar_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
