# Generated by Django 6.0.4 on 2026-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload project thumbnail image', null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.CharField(blank=True, help_text='Auto-assigned by AI (Beginner, Intermediate, Pro)', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='spec',
            field=models.TextField(blank=True, help_text='Paste the technical specification here for AI auto-categorization'),
        ),
    ]
