# Generated by Django 6.0.4 on 2026-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_projectcategory_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload team member photo', null=True, upload_to='team/'),
        ),
    ]
