# Generated by Django 6.0.4 on 2026-04-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_remove_teammember_avatar_url_teammember_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('lead', 'Club Lead'), ('co_lead', 'Co-Lead'), ('head', 'Department Head'), ('treasurer', 'Treasurer'), ('member', 'Core Member'), ('alumni', 'Alumni')], default='member', max_length=20),
        ),
    ]
