# Generated by Django 6.0.4 on 2026-04-26 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_teammember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the applicant', max_length=200)),
                ('email', models.EmailField(help_text='College email (must end with @ritroorkee.com)', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Only @ritroorkee.com email addresses are allowed.', regex='^.+@ritroorkee\\.com$')])),
                ('whatsapp_number', models.CharField(help_text='WhatsApp number for team communication', max_length=15)),
                ('roll_number', models.CharField(help_text='College roll number', max_length=30, unique=True)),
                ('branch', models.CharField(choices=[('ece', 'Electronics & Communication Engineering (ECE)'), ('cse', 'Computer Science & Engineering (CSE)'), ('iot', 'Internet of Things (IoT)'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('ee', 'Electrical Engineering'), ('other', 'Other')], max_length=20)),
                ('current_year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=5)),
                ('domain_of_interest', models.CharField(choices=[('electronics_iot', '⚙️ Core Electronics & IoT'), ('software_web', '💻 Software & Web Development'), ('robotics', '🤖 Robotics & Autonomous Systems'), ('uiux_content', '🎨 UI/UX Design & Content Management')], max_length=30)),
                ('skill_level', models.CharField(choices=[('beginner', 'Absolute Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('motivation', models.TextField(help_text='Why do you want to join CECP?')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile (optional)')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile (optional)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Club Head who reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='landing.clubmember')),
            ],
            options={
                'verbose_name': 'Club Application',
                'verbose_name_plural': 'Club Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
