# Generated by Django 6.0.4 on 2026-04-26 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_clubapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Django user who submitted this application (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
