# Generated by Django 6.0.4 on 2026-04-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_clubapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Professional profile photo', null=True, upload_to='application_photos/'),
        ),
    ]
