# Generated by Django 6.0.4 on 2026-04-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_clubapplication_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('lead', 'Club Lead'), ('co_lead', 'Co-Lead'), ('head', 'Department Head'), ('treasurer', 'Treasurer'), ('member', 'Core Member'), ('alumni', 'Alumni')], help_text='Role to automatically assign on the public Team page upon approval', max_length=20, null=True),
        ),
    ]
