# Generated by Django 6.0.4 on 2026-04-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_clubapplication_assigned_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='send_notification_email',
            field=models.BooleanField(default=False, help_text='Check this box and save to manually trigger an email notification based on the current status.'),
        ),
    ]
