# Generated by Django 6.0.4 on 2026-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course_and_branch',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('ECE', 'Electronics and Communication Engineering (ECE)'), ('CSE', 'Computer Science (CSE)'), ('AI/ML', 'Artificial Intelligence (AI/ML)'), ('CE', 'Civil Engineering (CE)'), ('IT', 'Information Technology (IT)'), ('EE', 'Electrical Engineering (EE)')], help_text='Only applicable for B.Tech', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('M.Tech', 'M.Tech')], max_length=20, null=True),
        ),
    ]
