# Generated by Django 6.0.4 on 2026-04-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_remove_userprofile_course_and_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='title',
        ),
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('advisor', 'Faculty Advisor'), ('head', 'Club Head'), ('core', 'Core Team'), ('member', 'Club Member')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='e.g., Web Master, Hardware Lead', max_length=100),
        ),
    ]
