# Generated by Django 6.0.4 on 2026-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_remove_teammember_github_url_remove_teammember_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='assigned_category',
            field=models.CharField(choices=[('advisor', 'Faculty Advisor'), ('head', 'Club Head'), ('core', 'Core Team'), ('member', 'Club Member')], default='member', help_text='Category on the public Team page', max_length=20),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='assigned_role',
            field=models.CharField(blank=True, help_text='Specific role/title (e.g., Web Master, Hardware Lead)', max_length=100, null=True),
        ),
    ]
