# Generated by Django 6.0.4 on 2026-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_clubapplication_assigned_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AlterModelOptions(
            name='clubmember',
            options={'ordering': ['category', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='clubmember',
            name='category',
            field=models.CharField(choices=[('advisor', 'Faculty Advisor'), ('head', 'Club Head'), ('core', 'Core Team'), ('member', 'Club Member')], default='member', help_text='Category on the public Team page (advisor / head / core / member)', max_length=20),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='display_role',
            field=models.CharField(blank=True, help_text="Specific title shown on Team page (e.g., 'Web Master', 'Hardware Lead')", max_length=100),
        ),
    ]
