# Generated by Django 6.0.4 on 2026-05-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_clubmember_single_source_of_truth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog title', max_length=200)),
                ('content', models.TextField(help_text='Blog content')),
                ('image', models.ImageField(blank=True, help_text='Cover image', null=True, upload_to='blogs/')),
                ('category_tag', models.CharField(blank=True, help_text='e.g., AI & Vision', max_length=50)),
                ('read_time', models.CharField(blank=True, default='5 min read', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='landing.clubmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
