# Generated by Django 6.0.4 on 2026-05-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
