# Generated by Django 6.0.4 on 2026-05-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_project_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmember',
            old_name='avatar',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='clubmember',
            name='display_name',
            field=models.CharField(blank=True, help_text='Specific title/name shown on Team page', max_length=200),
        ),
    ]
