# Generated by Django 6.0.4 on 2026-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_rename_avatar_clubmember_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='quote',
            field=models.CharField(blank=True, help_text='Your personal quote or signature phrase', max_length=255),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='quote',
            field=models.CharField(blank=True, help_text='A personal quote or signature phrase.', max_length=255),
        ),
    ]
