# Generated by Django 6.0.4 on 2026-05-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_clubapplication_quote_clubmember_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Resume (PDF)', null=True, upload_to='application_resumes/'),
        ),
    ]
