# Generated by Django 6.0.4 on 2026-05-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_add_quote_to_userprofile'),
        ('landing', '0020_clubapplication_resume'),
    ]

    operations = [
    ]
