# Generated by Django 6.0.4 on 2026-05-06 07:11

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_merge_20260506_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='email',
            field=models.EmailField(db_index=True, help_text='College email (must end with @ritroorkee.com)', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Only @ritroorkee.com email addresses are allowed.', regex='^.+@ritroorkee\\.com$')]),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Resume (PDF)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='application_resumes/'),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
