# Generated by Django 6.0.4 on 2026-05-06 17:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_alter_clubapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='personal_email',
            field=models.EmailField(db_index=True, help_text='Personal Gmail ID (used for website login)', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='resume',
            field=models.FileField(help_text='Resume (PDF)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='application_resumes/'),
        ),
    ]
