# Generated by Django 6.0.4 on 2026-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_clubapplication_personal_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('event_type', models.CharField(choices=[('Hackathon', 'Hackathon'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Talk', 'Talk'), ('Other', 'Other')], default='Other', max_length=50)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live Now', 'Live Now'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing')], default='Upcoming', max_length=50)),
                ('description', models.TextField(help_text='Brief event description')),
                ('date_range', models.CharField(help_text='e.g., 24-26 May 2025', max_length=100)),
                ('location', models.CharField(help_text='e.g., CECP, Bhopal', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Event cover image', null=True, upload_to='events/')),
                ('is_featured', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, help_text='Registration or View Details URL')),
                ('action_text', models.CharField(default='Register Now', help_text='Text for the button (e.g., Register Now, View Details, View Highlights)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
