# Generated by Django 6.0.4 on 2026-05-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_clubapplication_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(blank=True, help_text='The primary lead of this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='landing.clubmember'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or demo video URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='Project year'),
        ),
        migrations.CreateModel(
            name='ProjectAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Top 10 Finalist — OpenAI Hackathon National Finals', max_length=300)),
                ('achievement_type', models.CharField(choices=[('competition', 'Competition / Hackathon'), ('award', 'Award / Recognition'), ('publication', 'Publication / Paper'), ('milestone', 'Project Milestone'), ('deployment', 'Deployment / Launch')], default='competition', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Details about the achievement')),
                ('event_name', models.CharField(blank=True, help_text='e.g., Technomax 2025, OpenAI Hackathon 2026', max_length=200)),
                ('position', models.CharField(blank=True, help_text='e.g., 1st Place, Top 10 Finalist, Runner Up', max_length=100)),
                ('date', models.DateField(help_text='Date of the achievement')),
                ('certificate_url', models.URLField(blank=True, help_text='Link to certificate or proof')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='The project this achievement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='landing.project')),
            ],
            options={
                'verbose_name': 'Project Achievement',
                'verbose_name_plural': 'Project Achievements',
                'ordering': ['-date'],
            },
        ),
    ]
