# Generated by Django 6.0.4 on 2026-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_project_project_lead_project_video_url_project_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectachievement',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload certificate file (PDF/Image)', null=True, upload_to='achievements/certificates/'),
        ),
    ]
