# Generated by Django 6.0.4 on 2026-05-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='action_text',
            field=models.CharField(default='Explore', help_text='Action button text', max_length=50),
        ),
        migrations.AddField(
            model_name='initiative',
            name='action_url',
            field=models.URLField(blank=True, help_text='Action URL'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the card', null=True, upload_to='initiatives/'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='status',
            field=models.CharField(default='Active', help_text='e.g. Active, Upcoming', max_length=50),
        ),
        migrations.AddField(
            model_name='initiative',
            name='tag',
            field=models.CharField(default='Core Vertical', help_text='e.g. Core Vertical, Special Project', max_length=50),
        ),
    ]
