# Generated by Django 6.0.4 on 2026-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_projectachievement_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_team_members',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts [{'name': '...', 'email': '...'}] for unregistered teammates"),
        ),
    ]
