# Generated by Django 6.0.4 on 2026-05-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_initiative_action_text_initiative_action_url_and_more'),
        ('landing', '0026_project_external_team_members'),
    ]

    operations = [
    ]
