# Generated by Django 6.0.4 on 2026-05-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_merge_20260507_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='action_text',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='image',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='status',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='tag',
        ),
        migrations.AddField(
            model_name='clubmember',
            name='area_of_interest',
            field=models.CharField(blank=True, help_text='e.g., Embedded Systems, AI, Web Dev', max_length=255),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='core_technologies',
            field=models.CharField(blank=True, help_text='Comma-separated skills (e.g., Python, React, IoT)', max_length=255),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='experience',
            field=models.TextField(blank=True, help_text='Internships, past roles, or major accomplishments'),
        ),
    ]
