# Generated by Django 6.0.4 on 2026-05-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_merge_20260507_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='action_text',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='image',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='status',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='tag',
        ),
    ]
