# Generated by Django 6.0.4 on 2026-05-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_merge_20260507_0144'),
    ]

    operations = [
        # These removals are already handled by
        # 0028_delete_event_remove_initiative_action_text_and_more
        # Keeping this as a no-op to preserve the migration graph.
    ]
