# Generated by Django 6.0.4 on 2026-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_delete_event_remove_initiative_action_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_hosted', models.CharField(default='25+', help_text='e.g., 25+', max_length=50)),
                ('participants', models.CharField(default='2000+', help_text='e.g., 2000+', max_length=50)),
                ('winners_crowned', models.CharField(default='50+', help_text='e.g., 50+', max_length=50)),
                ('collaborations', models.CharField(default='10+', help_text='e.g., 10+', max_length=50)),
            ],
            options={
                'verbose_name': 'Event Stat',
                'verbose_name_plural': 'Event Stats',
            },
        ),
    ]
