# Generated by Django 6.0.4 on 2026-05-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_delete_event_remove_initiative_action_text_and_more'),
        ('landing', '0028_remove_initiative_action_text_and_more'),
    ]

    operations = [
    ]
