# Generated by Django 6.0.4 on 2026-05-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_merge_20260507_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentation_file',
            field=models.FileField(blank=True, help_text='Upload documentation file (PDF/DOC/PPT)', null=True, upload_to='projects/docs/'),
        ),
    ]
