# Generated by Django 6.0.4 on 2026-05-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_eventstat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmember',
            options={'ordering': ['display_order', 'category', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='clubmember',
            name='display_order',
            field=models.PositiveIntegerField(default=999, help_text='Order in which this member appears on the frontend.'),
        ),
    ]
