# Generated by Django 6.0.4 on 2026-05-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_alter_clubmember_options_clubmember_display_order'),
        ('landing', '0030_event_project_documentation_file'),
    ]

    operations = [
    ]
