# Generated by Django 6.0.4 on 2026-05-07 13:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0031_merge_20260507_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documentation_file',
            field=models.FileField(blank=True, help_text='Upload documentation file (PDF/DOC/PPT)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='projects/docs/'),
        ),
        migrations.AlterField(
            model_name='projectachievement',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload certificate file (PDF/Image)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='achievements/certificates/'),
        ),
    ]
