# Generated by Django 6.0.4 on 2026-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_alter_project_documentation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements_summary',
            field=models.TextField(blank=True, help_text='Certifications, awards, or competition results', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area_of_interest',
            field=models.CharField(blank=True, help_text='e.g., Robotics, AI, Embedded Systems', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='core_technologies',
            field=models.TextField(blank=True, help_text='List your technical skills (e.g., Python, Arduino, React)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='future_goals',
            field=models.TextField(blank=True, help_text='Career aspirations or future research goals', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_website',
            field=models.URLField(blank=True, help_text='Portfolio or personal blog', null=True),
        ),
    ]
