# Generated by Django 6.0.4 on 2026-05-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_sitesettings'),
        ('landing', '0033_userprofile_achievements_summary_and_more'),
    ]

    operations = [
    ]
