# Generated by Django 6.0.4 on 2026-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_merge_20260507_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements_summary',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='area_of_interest',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='future_goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='personal_website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_goals',
            field=models.TextField(blank=True, help_text='Where do you see yourself in 5 years? Your long-term ambitions.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='future_field',
            field=models.CharField(blank=True, help_text='The field you want to pursue (e.g., Robotics, AI Research, Software Engineering)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_interests',
            field=models.CharField(blank=True, help_text='Hobbies or things you love (e.g., Playing Guitar, Sketching, Chess)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professional_bio',
            field=models.TextField(blank=True, help_text='A brief professional summary of your journey and skills.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='core_technologies',
            field=models.CharField(blank=True, help_text='Skills you are proficient in (e.g., Python, React, IoT)', max_length=255, null=True),
        ),
    ]
