# Generated by Django 6.0.4 on 2026-05-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_delete_sitesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
