# Generated by Django 6.0.4 on 2026-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0036_userprofile_leetcode_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_languages_cache',
            field=models.JSONField(blank=True, default=None, help_text='Cached aggregated language stats from GitHub', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_repos_cache',
            field=models.JSONField(blank=True, default=None, help_text='Cached list of GitHub repos fetched from the API', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_github_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
