# Generated by Django 6.0.4 on 2026-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0039_auto_deactivate_non_approved_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_application_open', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
