# Generated by Django 6.0.4 on 2026-05-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0040_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='is_application_open',
            field=models.BooleanField(default=False, verbose_name='Application Portal Open'),
        ),
    ]
