# Generated by Django 6.0.4 on 2026-05-10 20:20

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0041_alter_sitesettings_is_application_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image', max_length=500, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Professional profile photo', max_length=500, null=True, upload_to='application_photos/'),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='resume',
            field=models.FileField(help_text='Resume (PDF)', max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='application_resumes/'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Event cover image', max_length=500, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='documentation_file',
            field=models.FileField(blank=True, help_text='Upload documentation file (PDF/DOC/PPT)', max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='projects/docs/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project thumbnail', max_length=500, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectachievement',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload certificate file (PDF/Image)', max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='achievements/certificates/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_pics/'),
        ),
    ]
