# Generated by Django 6.0.4 on 2026-05-11 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0042_alter_blog_image_alter_clubapplication_profile_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_faculty_application_open',
            field=models.BooleanField(default=False, verbose_name='Faculty Recruitment Open'),
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.TextField(blank=True, help_text='Comma-separated areas of research')),
                ('publications', models.TextField(blank=True, help_text='List of notable publications')),
                ('google_scholar_link', models.URLField(blank=True)),
                ('orcid', models.CharField(blank=True, help_text='ORCID ID', max_length=50)),
                ('experience_years', models.IntegerField(default=0)),
                ('awards', models.TextField(blank=True, help_text='Notable awards and honors')),
                ('students_mentored', models.IntegerField(default=0)),
                ('projects_guided', models.IntegerField(default=0)),
                ('research_papers_count', models.IntegerField(default=0)),
                ('workshops_conducted', models.IntegerField(default=0)),
                ('grants_received', models.CharField(blank=True, help_text="e.g., '12L+'", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
