# Generated by Django 6.0.4 on 2026-05-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0043_sitesettings_is_faculty_application_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='core_expertise',
            field=models.TextField(blank=True, help_text='Comma-separated core technologies/expertise'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='experience_timeline',
            field=models.TextField(blank=True, help_text="Timeline items separated by '|'"),
        ),
    ]
