# Generated by Django 6.0.4 on 2026-05-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0044_facultyprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='achievements',
            field=models.TextField(blank=True, help_text='List of notable professional achievements'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='awards_count',
            field=models.IntegerField(default=0, help_text='Number of awards received'),
        ),
    ]
