# Generated by Django 6.0.4 on 2026-05-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0045_facultyprofile_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Department (e.g. CSE, ECE, ME)', max_length=100),
        ),
    ]
