# Generated by Django 6.0.4 on 2026-05-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0046_facultyprofile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quote',
            field=models.CharField(blank=True, help_text='Your personal quote', max_length=255, null=True),
        ),
    ]
