# Generated by Django 6.0.4 on 2026-06-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0047_alter_project_options_alter_userprofile_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Personal portfolio, Linktree, or any other personal website URL', max_length=500, null=True),
        ),
    ]
